"""add_procurement_tables_phase5

Revision ID: 35340544bd45
Revises: 
Create Date: 2026-01-01 21:13:03.467512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '35340544bd45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_evidence_extended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('sub_classification', sa.String(), nullable=True),
    sa.Column('legal_basis', sa.String(), nullable=True),
    sa.Column('financial_impact_rub', sa.Float(), nullable=True),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('mitigation_cost_rub', sa.Float(), nullable=True),
    sa.Column('mitigation_time_days', sa.Integer(), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=True),
    sa.Column('raw_extract', sa.Text(), nullable=True),
    sa.Column('applicable_to_procurement_type', sa.JSON(), nullable=True),
    sa.Column('reference_in_kb', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_evidence_extended_analysis_id'), 'analysis_evidence_extended', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_extended_created_at'), 'analysis_evidence_extended', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_extended_evidence_id'), 'analysis_evidence_extended', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_analysis_evidence_extended_id'), 'analysis_evidence_extended', ['id'], unique=False)
    op.create_table('procurement_blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('sub_classification', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(), nullable=True),
    sa.Column('is_mitigable', sa.Boolean(), nullable=True),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('mitigation_cost', sa.Float(), nullable=True),
    sa.Column('mitigation_time_days', sa.Integer(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('kb_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_blockers_analysis_id'), 'procurement_blockers', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_procurement_blockers_created_at'), 'procurement_blockers', ['created_at'], unique=False)
    op.create_index(op.f('ix_procurement_blockers_id'), 'procurement_blockers', ['id'], unique=False)
    op.create_table('procurement_decisions_extended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('iun', sa.Integer(), nullable=False),
    sa.Column('decision_grounds', sa.Text(), nullable=False),
    sa.Column('critical_parameters', sa.JSON(), nullable=True),
    sa.Column('financial_impact', sa.JSON(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('kb_references', sa.JSON(), nullable=True),
    sa.Column('procurement_law', sa.String(), nullable=True),
    sa.Column('nmck', sa.Float(), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_decisions_extended_analysis_id'), 'procurement_decisions_extended', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_procurement_decisions_extended_created_at'), 'procurement_decisions_extended', ['created_at'], unique=False)
    op.create_index(op.f('ix_procurement_decisions_extended_id'), 'procurement_decisions_extended', ['id'], unique=False)
    op.create_table('procurement_knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('kb_path', sa.String(), nullable=False),
    sa.Column('kb_category', sa.String(), nullable=True),
    sa.Column('kb_title', sa.String(), nullable=True),
    sa.Column('query_used', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_knowledge_base_analysis_id'), 'procurement_knowledge_base', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_procurement_knowledge_base_created_at'), 'procurement_knowledge_base', ['created_at'], unique=False)
    op.create_index(op.f('ix_procurement_knowledge_base_id'), 'procurement_knowledge_base', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_knowledge_base_package_id'), 'procurement_knowledge_base', ['package_id'], unique=False)
    
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    # В SQLite JSON хранится как TEXT, что работает нормально
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('analyses', 'user_decision',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
    op.drop_index(op.f('idx_analyses_created_at'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_industry'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_industry_created'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_is_demo'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_score'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_session_id'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_user_created'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_verdict'), table_name='analyses')
    
    # SQLite не поддерживает DROP CONSTRAINT
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint(None, 'decision_records', type_='foreignkey')
    op.drop_index(op.f('idx_demo_sessions_created_at'), table_name='demo_sessions')
    op.drop_index(op.f('idx_demo_sessions_last_analysis'), table_name='demo_sessions')
    
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('package_analyses', 'user_decision',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
    op.drop_index(op.f('idx_package_analyses_created_at'), table_name='package_analyses')
    op.drop_index(op.f('idx_package_analyses_user_id'), table_name='package_analyses')
    op.drop_index(op.f('idx_usage_user_month'), table_name='usage')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_plan_type'), table_name='users')
    op.drop_index(op.f('idx_users_tariff_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_tariff_id'), 'users', ['tariff_id'], unique=False)
    op.create_index(op.f('idx_users_plan_type'), 'users', ['plan_type'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_usage_user_month'), 'usage', ['user_id', 'month'], unique=False)
    op.create_index(op.f('idx_package_analyses_user_id'), 'package_analyses', ['user_id'], unique=False)
    op.create_index(op.f('idx_package_analyses_created_at'), 'package_analyses', ['created_at'], unique=False)
    
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('package_analyses', 'user_decision',
                   existing_type=sa.JSON(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.create_index(op.f('idx_demo_sessions_last_analysis'), 'demo_sessions', ['last_analysis_at'], unique=False)
    op.create_index(op.f('idx_demo_sessions_created_at'), 'demo_sessions', ['created_at'], unique=False)
    
    # SQLite не поддерживает CREATE FOREIGN KEY через ALTER TABLE
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.create_foreign_key(None, 'decision_records', 'package_analyses', ['package_id'], ['package_id'])
    op.create_index(op.f('idx_analyses_verdict'), 'analyses', ['verdict'], unique=False)
    op.create_index(op.f('idx_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_index(op.f('idx_analyses_user_created'), 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_analyses_session_id'), 'analyses', ['session_id'], unique=False)
    op.create_index(op.f('idx_analyses_score'), 'analyses', ['score'], unique=False)
    op.create_index(op.f('idx_analyses_is_demo'), 'analyses', ['is_demo'], unique=False)
    op.create_index(op.f('idx_analyses_industry_created'), 'analyses', ['industry', 'created_at'], unique=False)
    op.create_index(op.f('idx_analyses_industry'), 'analyses', ['industry'], unique=False)
    op.create_index(op.f('idx_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('analyses', 'user_decision',
                   existing_type=sa.JSON(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.drop_index(op.f('ix_procurement_knowledge_base_package_id'), table_name='procurement_knowledge_base')
    op.drop_index(op.f('ix_procurement_knowledge_base_id'), table_name='procurement_knowledge_base')
    op.drop_index(op.f('ix_procurement_knowledge_base_created_at'), table_name='procurement_knowledge_base')
    op.drop_index(op.f('ix_procurement_knowledge_base_analysis_id'), table_name='procurement_knowledge_base')
    op.drop_table('procurement_knowledge_base')
    op.drop_index(op.f('ix_procurement_decisions_extended_id'), table_name='procurement_decisions_extended')
    op.drop_index(op.f('ix_procurement_decisions_extended_created_at'), table_name='procurement_decisions_extended')
    op.drop_index(op.f('ix_procurement_decisions_extended_analysis_id'), table_name='procurement_decisions_extended')
    op.drop_table('procurement_decisions_extended')
    op.drop_index(op.f('ix_procurement_blockers_id'), table_name='procurement_blockers')
    op.drop_index(op.f('ix_procurement_blockers_created_at'), table_name='procurement_blockers')
    op.drop_index(op.f('ix_procurement_blockers_analysis_id'), table_name='procurement_blockers')
    op.drop_table('procurement_blockers')
    op.drop_index(op.f('ix_analysis_evidence_extended_id'), table_name='analysis_evidence_extended')
    op.drop_index(op.f('ix_analysis_evidence_extended_evidence_id'), table_name='analysis_evidence_extended')
    op.drop_index(op.f('ix_analysis_evidence_extended_created_at'), table_name='analysis_evidence_extended')
    op.drop_index(op.f('ix_analysis_evidence_extended_analysis_id'), table_name='analysis_evidence_extended')
    op.drop_table('analysis_evidence_extended')
    # ### end Alembic commands ###
